# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: echo Starting Build....
  displayName: 'Start Build'

- script: echo Restoring Packages....
  displayName: 'Restoring packages'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '''src\Observability\Observability.csproj'''
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- script: echo Starting Publish....
  displayName: 'Publishing artifacts'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '''src\Observability\Observability.csproj'''
    arguments: '-o .\publish'
    zipAfterPublish: false
    modifyOutputPath: false
    feedsToUse: 'select'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
