# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: sdk

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
   # projects: 'src\Observability\Observability.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './src/Observability/Observability.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: src\Observability\Observability.csproj'
    arguments: '-o .\publish'
    zipAfterPublish: false
    modifyOutputPath: false
    feedsToUse: 'select'
